Name=input("enter name:    ")
Mobileno=input("enter mobileno:   ")
Mail_id=input("enter mail id:    ")
College_name=input("College name:      ")
Branch=input("Branch:    ")
print("........STUDENT PROFILE........")
print("enter name:        ",Name)
print("enter mobileno:     ",Mobileno)
print("enter mail id:    ",Mail_id)
print("College name:      ",College_name)
print("Branch:     ",Branch)
